name: reachbot
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - absl-py
      - addict
      - appdirs
      - boto3
      - botocore
      - cachetools
      - certifi
      - chardet
      - charset-normalizer
      - click
      - configparser
      - contourpy
      - cycler
      - docker-pycreds
      - dowel
      - fonttools
      - gitdb
      - gitpython
      - google-auth
      - google-auth-oauthlib
      - grpcio
      - idna
      - imageio
      - importlib-metadata
      - importlib-resources
      - jmespath
      - kiwisolver
      - lazy-loader
      - markdown
      - markdown-it-py
      - markupsafe
      - matplotlib
      - mdurl
      - mmcv
      - mmdet
      - mmengine
      - networkx
      - numpy
      - nvidia-ml-py3
      - oauthlib
      - opencv-python
      - packaging
      - pathtools
      - pillow
      - platformdirs
      - prettytable
      - protobuf
      - psutil
      - pyasn1
      - pyasn1-modules
      - pycocotools
      - pygments
      - pyparsing
      - python-dateutil
      - pywavelets
      - pyyaml
      - requests
      - requests-oauthlib
      - rich
      - rsa
      - s3transfer
      - scikit-image
      - scipy
      - sentry-sdk
      - setproctitle
      - shapely
      - six
      - smmap
      - tabulate
      - tensorboard
      - tensorboard-data-server
      - tensorboardx
      - termcolor
      - terminaltables
      - tifffile
      - tomli
      - toolbox==1.11.0
      - torch
      - torchaudio
      - torchvision
      - typing-extensions
      - urllib3
      - wandb
      - wcwidth
      - werkzeug
      - yapf
      - zipp

